test: &default

  # Credentials for New APIs
  mode: sandbox
  rest_endpoint: 'https://api.sandbox.paypal.com'
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Mode can be 'live' or 'sandbox'

development:
  <<: *default

production:
  #<<: *default
  mode: live
  rest_endpoint: 'https://api.paypal.com'
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


